// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8Kop8FVrrcbqRjT9pil8-XZkToqlhCS0',
    appId: '1:186621583380:web:5a526d5574a2b868db8701',
    messagingSenderId: '186621583380',
    projectId: 'okello-billtool',
    authDomain: 'okello-billtool.firebaseapp.com',
    storageBucket: 'okello-billtool.appspot.com',
    measurementId: 'G-CGN6WPJK5N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW00HCxXv0THYx771g-kqhSBpsm8Q_B8s',
    appId: '1:186621583380:android:f8c95fcda78d73b7db8701',
    messagingSenderId: '186621583380',
    projectId: 'okello-billtool',
    storageBucket: 'okello-billtool.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9NJmsyYvM6Q2tGYiAgB7cgk2NeplCxfo',
    appId: '1:186621583380:ios:e52967a943c431cddb8701',
    messagingSenderId: '186621583380',
    projectId: 'okello-billtool',
    storageBucket: 'okello-billtool.appspot.com',
    androidClientId: '186621583380-75vjime96mrfsj218k9mc79lldtu6900.apps.googleusercontent.com',
    iosClientId: '186621583380-nf66a17t006o53n9fmod5lknl5lnejg1.apps.googleusercontent.com',
    iosBundleId: 'com.example.okelloBillTool',
  );
}
